ehome:
  serverIp: ${ehome_server_io:192.168.6.86}
  serverPort: ${ehome_server_port:7660}
  udpAlarmServerIp: ${ehome_alarm_udp_server_ip:192.168.6.86}
  udpAlarmServerPort: ${ehome_alarm_udp_server_port:7200}
  tcpAlarmServerIp: ${ehome_alarm_tcp_server_ip:192.168.6.86}
  tcpAlarmServerPort: ${ehome_alarm_tcp_server_port:7280}
  pictureServerIp: ${ehome_picture_server_ip:192.168.6.86}
  pictureServerPort: ${ehome_picture_server_port:8080}

server:
  port: 8080
